name: ogcisum_web
services:
  backend:
    container_name: ogcisum_web
    build: .
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./build:/app/build